const primaryEmotions = [
  { id: 1, name: "Fearful" },
  { id: 2, name: "Angry" },
  { id: 3, name: "Disgusted" },
  { id: 4, name: "Sad" },
  { id: 5, name: "Happy" },
  { id: 6, name: "Surprised" },
  { id: 7, name: "Bad" },
];

const secondaryEmotions = [
  { id: 1, primaryId: 1, name: "Scared" },
  { id: 2, primaryId: 1, name: "Anxious" },
  { id: 3, primaryId: 1, name: "Insecure" },
  { id: 4, primaryId: 1, name: "Weak" },
  { id: 5, primaryId: 1, name: "Rejected" },
  { id: 6, primaryId: 1, name: "Threatened" },
  { id: 7, primaryId: 2, name: "Let Down" },
  { id: 8, primaryId: 2, name: "Humiliated" },
  { id: 9, primaryId: 2, name: "Bitter" },
  { id: 10, primaryId: 2, name: "Mad" },
  { id: 11, primaryId: 2, name: "Aggressive" },
  { id: 12, primaryId: 2, name: "Frustrated" },
  { id: 13, primaryId: 2, name: "Distant" },
  { id: 14, primaryId: 2, name: "Critical" },
  { id: 15, primaryId: 3, name: "Disapproving" },
  { id: 16, primaryId: 3, name: "Disappointed" },
  { id: 17, primaryId: 3, name: "Awful" },
  { id: 18, primaryId: 3, name: "Repelled" },
  { id: 19, primaryId: 4, name: "Hurt" },
  { id: 20, primaryId: 4, name: "Depressed" },
  { id: 21, primaryId: 4, name: "Guilty" },
  { id: 22, primaryId: 4, name: "Despair" },
  { id: 23, primaryId: 4, name: "Vulnerable" },
  { id: 24, primaryId: 4, name: "Lonely" },
  { id: 25, primaryId: 5, name: "Playful" },
  { id: 26, primaryId: 5, name: "Content" },
  { id: 27, primaryId: 5, name: "Interested" },
  { id: 28, primaryId: 5, name: "Proud" },
  { id: 29, primaryId: 5, name: "Accepted" },
  { id: 30, primaryId: 5, name: "Powerful" },
  { id: 31, primaryId: 5, name: "Peaceful" },
  { id: 32, primaryId: 5, name: "Trusting" },
  { id: 33, primaryId: 5, name: "Optimistic" },
  { id: 34, primaryId: 6, name: "Startled" },
  { id: 35, primaryId: 6, name: "Confused" },
  { id: 36, primaryId: 6, name: "Amazed" },
  { id: 37, primaryId: 6, name: "Excited" },
  { id: 38, primaryId: 7, name: "Bored" },
  { id: 39, primaryId: 7, name: "Busy" },
  { id: 40, primaryId: 7, name: "Stressed" },
  { id: 41, primaryId: 7, name: "Tired" },
];

const tertiaryEmotions = [
  { id: 1, secondaryId: 1, name: "Helpless" },
  { id: 2, secondaryId: 1, name: "Frightened" },
  { id: 3, secondaryId: 2, name: "Overwhelmed" },
  { id: 4, secondaryId: 2, name: "Worried" },
  { id: 5, secondaryId: 3, name: "Inadequate" },
  { id: 6, secondaryId: 3, name: "Inferior" },
  { id: 7, secondaryId: 4, name: "Worthless" },
  { id: 8, secondaryId: 4, name: "Insignificant" },
  { id: 9, secondaryId: 5, name: "Excluded" },
  { id: 10, secondaryId: 5, name: "Persecuted" },
  { id: 11, secondaryId: 6, name: "Nervous" },
  { id: 12, secondaryId: 6, name: "Exposed" },
  { id: 13, secondaryId: 7, name: "Betrayed" },
  { id: 14, secondaryId: 7, name: "Resentful" },
  { id: 15, secondaryId: 8, name: "Disrespected" },
  { id: 16, secondaryId: 8, name: "Ridiculed" },
  { id: 17, secondaryId: 9, name: "Indignant" },
  { id: 18, secondaryId: 9, name: "Violated" },
  { id: 19, secondaryId: 10, name: "Furious" },
  { id: 20, secondaryId: 10, name: "Jealous" },
  { id: 21, secondaryId: 11, name: "Provoked" },
  { id: 22, secondaryId: 11, name: "Hostile" },
  { id: 23, secondaryId: 12, name: "Infuriated" },
  { id: 24, secondaryId: 12, name: "Annoyed" },
  { id: 25, secondaryId: 13, name: "Withdrawn" },
  { id: 26, secondaryId: 13, name: "Numb" },
  { id: 27, secondaryId: 14, name: "Skeptical" },
  { id: 28, secondaryId: 14, name: "Dismissive" },
  { id: 29, secondaryId: 15, name: "Judgmental" },
  { id: 30, secondaryId: 15, name: "Embarrassed" },
  { id: 31, secondaryId: 16, name: "Appalled" },
  { id: 32, secondaryId: 16, name: "Revolted" },
  { id: 33, secondaryId: 17, name: "Nauseated" },
  { id: 34, secondaryId: 17, name: "Detestable" },
  { id: 35, secondaryId: 18, name: "Hesitant" },
  { id: 36, secondaryId: 18, name: "Horrified" },
  { id: 37, secondaryId: 19, name: "Embarrassed" },
  { id: 38, secondaryId: 19, name: "Disappointed" },
  { id: 39, secondaryId: 20, name: "Inferior" },
  { id: 40, secondaryId: 20, name: "Empty" },
  { id: 41, secondaryId: 21, name: "Remorseful" },
  { id: 42, secondaryId: 21, name: "Ashamed" },
  { id: 43, secondaryId: 22, name: "Powerless" },
  { id: 44, secondaryId: 22, name: "Grief" },
  { id: 45, secondaryId: 23, name: "Victimized" },
  { id: 46, secondaryId: 23, name: "Fragile" },
  { id: 47, secondaryId: 24, name: "Abandoned" },
  { id: 48, secondaryId: 24, name: "Isolated" },
  { id: 49, secondaryId: 25, name: "Aroused" },
  { id: 50, secondaryId: 25, name: "Cheeky" },
  { id: 51, secondaryId: 26, name: "Free" },
  { id: 52, secondaryId: 26, name: "Joyful" },
  { id: 53, secondaryId: 27, name: "Curious" },
  { id: 54, secondaryId: 27, name: "Inquisitive" },
  { id: 55, secondaryId: 28, name: "Successful" },
  { id: 56, secondaryId: 28, name: "Confident" },
  { id: 57, secondaryId: 29, name: "Respected" },
  { id: 58, secondaryId: 29, name: "Valued" },
  { id: 59, secondaryId: 30, name: "Courageous" },
  { id: 60, secondaryId: 30, name: "Creative" },
  { id: 61, secondaryId: 31, name: "Loving" },
  { id: 62, secondaryId: 31, name: "Thankful" },
  { id: 63, secondaryId: 32, name: "Sensitive" },
  { id: 64, secondaryId: 32, name: "Intimate" },
  { id: 65, secondaryId: 33, name: "Hopeful" },
  { id: 66, secondaryId: 33, name: "Inspired" },
  { id: 67, secondaryId: 34, name: "Shocked" },
  { id: 68, secondaryId: 34, name: "Dismayed" },
  { id: 69, secondaryId: 35, name: "Disillusioned" },
  { id: 70, secondaryId: 35, name: "Perplexed" },
  { id: 71, secondaryId: 36, name: "Astonished" },
  { id: 72, secondaryId: 36, name: "Awe" },
  { id: 73, secondaryId: 37, name: "Eager" },
  { id: 74, secondaryId: 37, name: "Energetic" },
  { id: 75, secondaryId: 38, name: "Apathetic" },
  { id: 76, secondaryId: 38, name: "Indifferent" },
  { id: 77, secondaryId: 39, name: "Pressured" },
  { id: 78, secondaryId: 39, name: "Rushed" },
  { id: 79, secondaryId: 40, name: "Overwhelmed" },
  { id: 80, secondaryId: 40, name: "Out of control" },
  { id: 81, secondaryId: 41, name: "Sleepy" },
  { id: 82, secondaryId: 41, name: "Unfocussed" },
];

export { primaryEmotions, secondaryEmotions, tertiaryEmotions };
